version: '3.7'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html/
        volumes:
            -   .:/var/www/html/
        networks:
            - app-network
    router:
        image: nginx:alpine
        container_name: router
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www/html/
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
    db:
        image: mysql:5.7.32
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_USERNAME: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

